import {useEffect,useRef,useState} from 'react';
import {Arena} from './Arena';
import {Brain} from './Brain';
import {Lab} from './Lab';
import {Engine,type Mode} from './engine';
import {CHANNELS,type Topology} from '../../../packages/protocol';
import {observation,type Difficulty} from '../../../packages/sim/core';
const modes:{id:Mode;label:string;icon:string}[]=[{id:'human',label:'Play',icon:'↗'},{id:'spectate',label:'Spectate',icon:'◉'},{id:'lab',label:'Training lab',icon:'⌘'},{id:'replay',label:'Replays',icon:'↺'}];
const labels:Record<Topology,string>={real:'Connectome topology',degree_randomized:'Degree-preserving random',weight_shuffled:'Weight-shuffled control',ordinary:'Size-matched recurrent',rule:'No-brain rules',random:'Random-action baseline'};
export function App(){
 const [engine]=useState(()=>new Engine());const [,refresh]=useState(0);const [layout,setLayout]=useState('split');const [channels,setChannels]=useState(false);const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{engine.connect();const timer=setInterval(()=>refresh(v=>v+1),100);if(import.meta.env.DEV)window.__FLYWEIGHT__={snapshot:()=>engine.snapshot(),scene:(name,seed=783,seconds=45)=>{engine.mode='spectate';engine.reset(seed,name,seconds*60);},pause:p=>{engine.paused=p;},exportReplay:()=>engine.exportReplay(),loadReplay:text=>engine.loadReplay(text),step:frames=>{if(Number.isInteger(frames)&&frames>0&&frames<=5400)for(let i=0;i<frames;i++)engine.advance();},engine};return()=>{clearInterval(timer);engine.destroy();delete window.__FLYWEIGHT__;};},[engine]);
 const s=engine.state,g=engine.graph,online=engine.online,mode=engine.mode,neural=!['rule','random'].includes(engine.topology),done=s.winner!==null;
 const save=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(engine.exportReplay())],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`flyweight-seed-${s.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const load=async(f?:File)=>{if(!f)return;try{if(f.size>1_000_000)throw Error('Replay must be under 1 MB');engine.loadReplay(await f.text());}catch(e){engine.error=e instanceof Error?e.message:'Invalid replay';}};
 const warning=!online?'LOCAL DEMO · Neural service unavailable or reconnecting. The opponent uses conventional rules; no neural activity is simulated.':g?.synthetic?'SYNTHETIC DATA · Generated fixture. No FlyWire neuron IDs or biological topology are active.':null;
 return <div className="app-shell"><header className="masthead"><a className="wordmark" href="/"><span className="brand-icon">f<span>•</span></span>flyweight<span className="version">EXPERIMENT 001</span></a><div className="header-right"><span className="local-dot"/> LOCAL RESEARCH BUILD <span className="version">v0.1</span><a href="#about" className="about-link">About the experiment ↗</a></div></header><main>
 <section className="intro"><div><div className="eyebrow">NEUROSCIENCE, MEET THE ARCADE.</div><h1>A connectome<br/>in the <span>ring.</span></h1><p>Real fly-brain wiring. An artificial fighter.<br/>A small experiment in what structure can do.</p></div><div className="intro-note"><span className="note-number">01—</span><p>Can a biological network<br/>learn an entirely new game?</p><span className="mono">DROSOPHILA MELANOGASTER<br/>FLYWIRE · MATERIALIZATION 783</span><div className="fly-mark" aria-hidden="true">✳</div></div></section>
 <div className="workspace-nav"><nav aria-label="Experiment mode">{modes.map(m=><button key={m.id} onClick={()=>engine.setMode(m.id)} className={mode===m.id?'active':''}><span>{m.icon}</span>{m.label}</button>)}</nav><div className="layout-control">{[['arena','Arena only'],['split','Split view'],['brain','Brain focus']].map(([id,label])=><button key={id} title={label} aria-label={label} aria-pressed={layout===id} className={layout===id?'selected':''} onClick={()=>setLayout(id)}>{id==='arena'?'▰':id==='split'?'◫':'⌘'}</button>)}</div></div>
 {warning&&<div className="warning" role="status"><span>!</span>{warning}</div>}<div className="mobile-warning">Play needs a keyboard and desktop screen. Spectate, training and replay controls are available here.</div>
 <section className={`experiment-grid layout-${layout} mode-${mode}`}><div className="arena-panel"><div className="panel-top"><span className="panel-label">{mode==='lab'?'01 / TRAINING LAB':mode==='replay'?'01 / REPLAY THEATRE':'01 / THE ARENA'}</span><span className="arena-status"><i className={!engine.paused&&!done?'lit':''}/>{mode==='lab'?'ADAPTER EVOLUTION':mode==='replay'?'RECORDED ACTIONS':engine.paused?'PAUSED':done?'ROUND COMPLETE':'LIVE SIMULATION'}</span></div>
 {mode==='lab'?<Lab engine={engine}/>:<><div className="match-hud">{[0,1].map((i)=><div key={i} className={i?'fighter-hud brain-fighter':'fighter-hud'}><div><span className={i?'fighter-indicator neural':'fighter-indicator'}/><strong>{i?online?'FLYWEIGHT':'DEMO AI':mode==='human'?'YOU':'RULE-BASED AI'}</strong><small>{i?neural?'RECURRENT':'BASELINE':mode==='human'?'HUMAN':engine.difficulty.toUpperCase()}</small></div><div className="health-track"><span style={{width:`${s.fighters[i].hp}%`}}/></div><span className="health-number">{s.fighters[i].hp} <small>/ 100</small></span></div>)}<div className="timer"><strong>{String(Math.max(0,Math.ceil((s.limit-s.frame)/60))).padStart(2,'0')}</strong><small>ROUND 01</small></div></div>
 <div className="stage"><Arena engine={engine}/><div className="stage-caption"><span>CONTROL SUBJECT <b>01</b></span><span>NETWORK SUBJECT <b>02</b></span></div>{(done||engine.paused)&&<div className="match-overlay"><span className="eyebrow">{done?'EXPERIMENT IN PROGRESS':'TAKE A BREATH'}</span><h2>{done?s.winner===2?'A draw.':s.winner===1?'Network wins.':mode==='human'?'You win.':'Rules win.':'Paused.'}</h2><p>{done?'One round is an observation, not a conclusion.':'The simulation is paused.'}</p><button className="primary" onClick={()=>{if(done){if(mode==='replay'&&engine.replay){engine.seek(0);engine.paused=false;}else engine.reset();}else engine.paused=false;}}>{done?'Run it again ↗':'Resume match ↗'}</button></div>}</div>
 <div className="arena-bottom"><span className="mono">SEED {s.seed} <span className="divider">/</span> FRAME {String(s.frame).padStart(4,'0')}</span><div><button aria-label={engine.paused?'Resume':'Pause'} onClick={()=>{engine.paused=!engine.paused;}}>{engine.paused?'▶ Resume':'Ⅱ Pause'}</button><button onClick={()=>engine.reset()}>↺ Restart</button><button onClick={save}>↓ Save replay</button></div></div>
 <div className="match-settings">{mode==='replay'?<><div className="replay-controls"><button onClick={()=>file.current?.click()}>↑ Open replay</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{void load(e.target.files?.[0]);e.target.value='';}}/><button disabled={!engine.actions.length} onClick={()=>engine.loadReplay(JSON.stringify(engine.exportReplay()))}>Watch current recording</button></div>{engine.replay&&<label className="seek-label">FRAME {engine.replayCursor} / {engine.replay.actions.length}<input aria-label="Replay frame" type="range" min="0" max={engine.replay.actions.length} value={engine.replayCursor} onChange={e=>engine.seek(Number(e.target.value))}/></label>}<small>Action log · integrity checked · neural activity is not recorded</small></>:<><label>OPPONENT<select aria-label="Opponent difficulty" value={engine.difficulty} onChange={e=>{engine.difficulty=e.target.value as Difficulty;engine.reset();}}><option value="easy">Easy · reactive</option><option value="medium">Medium · spacing</option><option value="hard">Hard · predictive</option></select></label><label>CONTROLLER<select aria-label="Controller topology" value={engine.topology} onChange={e=>{engine.topology=e.target.value as Topology;engine.reset();}}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button className="new-seed" onClick={()=>engine.reset((s.seed+1)>>>0)}>New seed ↗</button></>}</div></>}
 </div><aside className="brain-panel"><div className="panel-top"><span className="panel-label">02 / INSIDE THE NETWORK</span><span className="brain-live">{mode==='replay'?'SCHEMATIC':online&&neural?'● LIVE':'○ IDLE'}</span></div><div className="brain-title"><div><span className="eyebrow">ACTIVE SUBGRAPH</span><h2>{g?g.neurons.toLocaleString():'—'} <small>neurons</small></h2></div><span className="micro-tag">{g?.synthetic?'SYNTHETIC':g?'v783':'OFFLINE'}</span></div><Brain engine={engine}/><div className="graph-legend"><span><i className="input"/>Input</span><span><i/>Internal</span><span><i className="output"/>Output</span><span className="sample-note">SAMPLED VIEW · {g?.ids.length??0}</span></div><div className="edge-legend"><span>─ Excitatory</span><span>─ Inhibitory</span><small>Schematic, not anatomical</small></div><div className="network-metrics"><div><small>DIRECTED EDGES</small><strong>{g?.edge_count.toLocaleString()??'—'}</strong></div><div><small>MEAN |ACTIVITY|</small><strong>{mode==='replay'?'—':engine.aggregate.toFixed(4)}</strong></div></div><div className="action-readout"><span>SELECTED ACTION</span><strong>{mode==='replay'?'Recorded actions':online?engine.actionName:'Rule-based demo'} <b>↗</b></strong><div className="activity-meter">{Array.from({length:28},(_,i)=><i key={i} className={i<Math.min(28,Math.round(engine.aggregate*300))&&mode!=='replay'?'on':''}/>)}</div></div><div className="tick-row"><span>Brain tick <b>{online?engine.brainMs.toFixed(2):'—'} ms</b></span><span>Game tick <b>{engine.gameMs.toFixed(2)} ms</b></span></div><div className="controller-note"><span className="local-dot"/>{online?neural?'Approximate recurrent dynamics':'Conventional comparison baseline':'Local fallback controller'}<small>{engine.checkpoint==='seed-initialized'?'Seed-initialized adapters · untrained':engine.checkpoint}</small></div></aside></section>
 {engine.error&&<div className="error" role="alert">{engine.error}<button onClick={()=>{engine.error='';}}>Dismiss</button></div>}
 <div className="data-strip"><span className={online&&!g?.synthetic?'data-tag':'data-tag fallback'}>{online&&!g?.synthetic?'REAL CONNECTOME DATA':online?'SYNTHETIC FIXTURE':'LOCAL DEMO'}</span><p>{online&&!g?.synthetic?'FlyWire v783 topology and synapse counts. Artificial sensory and motor adapters.':online?'Generated graph fixture. Real-data replacement pipeline available.':'The game stays playable while the neural service is unavailable.'}</p><button onClick={()=>setChannels(!channels)}>{channels?'Hide interface −':'Inspect the interface +'}</button></div>
 {channels&&<section className="channel-panel"><div><h3>What enters the network</h3><p>Observations stimulate {g?.input_count??0} sensory candidates. Eight recurrent updates carry activity through the graph; the readout sees {g?.output_count??0} descending candidates only.</p></div><div className="channels">{CHANNELS.map((name,i)=><div key={name}><span>{String(i+1).padStart(2,'0')} {name}</span><b>{observation(s,1)[i].toFixed(2)}</b></div>)}</div></section>}
 <section className="controls-guide"><span className="eyebrow">TAKE THE CONTROLS</span>{[['A / D','Move'],['W','Jump'],['S','Block'],['J','Light'],['K','Heavy'],['L','Dodge'],['SPACE','Pause']].map(([key,label])=><div key={key}><kbd>{key}</kbd><span>{label}</span></div>)}</section>
 <footer id="about"><div><a className="wordmark" href="/">flyweight<span className="footer-star">✳</span></a><p>An experiment, not an organism.</p></div><p>A connectome-constrained AI experiment.<br/>Not a conscious fly or full-brain simulation.<br/>No claim of biological learning.</p><div className="footer-links"><a href="https://www.nature.com/articles/s41586-024-07763-9" target="_blank" rel="noreferrer">The scientific reference ↗</a><a href="https://github.com/philshiu/Drosophila_brain_model" target="_blank" rel="noreferrer">Data & model attribution ↗</a><span className="mono">LOCAL BY DESIGN. EXPLORATORY BY NATURE.</span></div></footer>
 </main></div>;
}
