import {useState} from 'react';
import {ACTIONS} from '../../../packages/protocol';
import {describeEvent,roundReward} from '../../../packages/sim/core';
import {Brain} from './Brain';
import type {Engine} from './engine';
export function DecisionPanels({engine}:{engine:Engine}){
 const [all,setAll]=useState(false);const live=engine.online&&engine.isNeural&&engine.mode!=='replay',obs=engine.inputs,s=engine.state;
 const scores=engine.scores.map((value,index)=>({value,index})).sort((a,b)=>b.value-a.value);const last=(s.events??[]).filter(e=>e.actor===1||e.target===1).at(-1);
 return <aside className="dual-panels"><section className="brain-panel fly-decisions"><div className="panel-top"><span className="identity fly"><b aria-hidden="true">✳</b> {engine.rightName}</span><span className="quiet-status">{engine.mode==='replay'?'Recorded':engine.paused?'Paused':live?'Live decision':engine.online?'Rule control':'Offline'}</span></div>
 <div className="flow-step"><span className="step-number">1</span><div><h3>What it can see</h3><p>{live&&obs.length?`Opponent ${obs[6]<.12?'close':'far'} · ${obs[7]?'attacking':obs[8]?'blocking':'not attacking'}`:'No live Fly Brain inputs'}</p></div></div>
 <div className="signal-chips">{live&&obs.length?<><span>Distance <b>{Math.round(obs[6]*1000)} px</b></span><span>Health <b>{Math.round(obs[9]*100)}%</b></span><span>Attack ready <b>{obs[17]?'Yes':'No'}</b></span></>:<span>{engine.mode==='replay'?'Replays contain actions, not recorded brain signals.':'The demo bot uses game rules. No brain signals are generated.'}</span>}</div>
 <div className="flow-step compact"><span className="step-number">2</span><div><h3>{live?'Signals through fixed fly wiring':'Controller signals'}</h3><p>{live?(engine.graph?.synthetic?'Synthetic fixture · not FlyWire wiring':'Real FlyWire connections · artificial neuron dynamics'):'Neural visualization inactive'}</p></div></div>
 <Brain engine={engine}/><p className="schematic-note">Sampled, schematic view. Hover for measured values.</p>
 <div className="flow-step compact"><span className="step-number">3</span><div><h3>What it chose</h3><strong className="chosen-action">{engine.mode==='replay'?ACTIONS[s.fighters[1].action]:engine.actionName}</strong></div></div>
 {live&&scores.length>0?<div className="score-list">{(all?scores:scores.slice(0,3)).map(({value,index})=><div key={index} className={engine.action===index?'chosen':''} title={`Raw motor readout score ${value.toFixed(6)}. ${engine.available[index]?'Available':'Unavailable in this combat state'}. Not a probability.`}><span>{ACTIONS[index]}{!engine.available[index]?' · unavailable':''}</span><b>{value.toFixed(3)}</b><i style={{width:`${Math.max(2,Math.min(100,Math.abs(value)*30))}%`}}/></div>)}<button onClick={()=>setAll(!all)}>{all?'Show fewer scores':'See all action scores'} {all?'−':'+'}</button><p>The highest available score wins. Scores are not probabilities.</p></div>:<p className="plain-trace">{engine.mode==='replay'?'This action comes from the saved match log.':engine.neuralRule??'The demo bot follows the same spacing and attack rules as a medium bot.'}</p>}
 <div className="decision-result"><span className="step-number">4</span><div><h3>Did it work?</h3><p>{last?describeEvent(last):'No attack result yet.'}</p><small>Round score: {roundReward(s,1).toFixed(1)} · no learning during play</small></div></div>
 </section><section className="bot-panel"><div className="panel-top"><span className="identity bot"><b aria-hidden="true">◆</b> {engine.mode==='human'?'YOU':'BOT'}</span><span className="quiet-status">{engine.mode==='human'?'Keyboard':`${engine.difficulty} difficulty`}</span></div><div className="bot-trace"><h3>{engine.mode==='human'?'Your input':'Why this action'}</h3><p>{engine.mode==='replay'?'Recorded action; live bot rules are not being rerun.':engine.mode==='human'?engine.humanDecision:engine.botDecision.reason}</p><span className="trace-arrow" aria-hidden="true">↓</span><strong>{ACTIONS[s.fighters[0].action]}</strong><small>{engine.mode==='human'?'You control this fighter.':'The bot uses explicit game rules, not a neural network.'}</small></div></section></aside>;
}

