import {Presentation3D} from './Presentation3D';
import type {Engine} from './engine';

const pct=(value?:number)=>value===undefined?'--':`${Math.round(value*100)}%`;

export function Overview({engine}:{engine:Engine}){
 const today=engine.research?.today,champion=engine.research?.current_champion,cert=engine.research?.certified_level,status=engine.research?.worker_status?.state??engine.research?.training_status??'idle';
 return <section className="overview-page"><div className="fight-card-hero"><Presentation3D engine={engine} variant="hero"/><div className="hero-copy"><div className="eyebrow">NEUROSCIENCE FIGHT NIGHT</div><h1>A fruit-fly connectome is learning to fight.</h1><p>The fight stays deterministic and 2D. The spectacle is a live presentation layer around real controller state, replayable matches, and recorded research evidence.</p><div className="hero-actions"><button className="primary" onClick={()=>engine.setMode('spectate')}>Watch live</button><button className="subtle" onClick={()=>engine.setMode('human')}>Fight the Fly</button><button className="subtle" onClick={()=>engine.setMode('research')}>Open research</button></div></div></div>
  <div className="broadcast-strip"><section><small>PROJECT DAY</small><strong>{today?.day??'--'}</strong><span>{today?.date??'waiting for daily report'}</span></section><section><small>CURRENT CHAMPION</small><strong>{champion?.checkpoint_id?.slice(-10)??engine.checkpoint.slice(-10)}</strong><span>{champion?.selection??'seed or canonical pointer'}</span></section><section><small>CERTIFIED LEVEL</small><strong>{cert?`${cert.level}/10`:'0/10'}</strong><span>{cert?`${pct(cert.win_rate)} over ${cert.matches} matches`:'no certification yet'}</span></section><section><small>TRAINING STATUS</small><strong>{status}</strong><span>{engine.online?'brain service online':'demo fallback active'}</span></section></div>
  <div className="story-grid"><section><h2>Watch</h2><p>See the purple fighter act from Fly Brain outputs while the green opponent follows conventional game rules.</p><button onClick={()=>engine.setMode('spectate')}>Enter broadcast</button></section><section><h2>Play</h2><p>Challenge the current Fly Brain champion with keyboard controls. Results can become replay-verified exhibition records.</p><button onClick={()=>engine.setMode('human')}>Start challenge</button></section><section><h2>Research</h2><p>Inspect candidates, ladder progress, topology controls, daily reports and the boundary between live state and historical evidence.</p><button onClick={()=>engine.setMode('research')}>Review evidence</button></section></div>
 </section>;
}

export function Leaderboard({engine}:{engine:Engine}){
 const matches=engine.humanMatches?.matches??[];
 return <section className="leaderboard-page"><div className="leaderboard-hero"><div><div className="eyebrow">HUMAN CHALLENGE</div><h2>Fight the Fly. Keep the receipts.</h2><p>Leaderboard entries come from verified human replays only. No account required; no unverified claims are accepted.</p></div><button className="primary" onClick={()=>engine.setMode('human')}>Start fight</button></div><div className="leaderboard-list">{matches.length?matches.map(match=><div key={match.id}><b>{match.result.result.replace('_',' ')}</b><span>Seed {match.match_seed}</span><span>Damage {Math.round(match.result.damage_dealt)} / taken {Math.round(match.result.damage_received)}</span><small>{match.replay_hash.slice(0,16)}</small></div>):<p>No verified human exhibition results yet. Finish a Play match and save the replay-ready result card.</p>}</div></section>;
}
