import {CHANNELS,type Topology} from '../../../packages/protocol';
import {observation} from '../../../packages/sim/core';
import type {Engine} from './engine';
export const TOPOLOGY_LABELS:Record<Topology,string>={real:'Fly Brain wiring',degree_randomized:'Randomized wiring · same degrees',weight_shuffled:'Shuffled connection weights',ordinary:'Ordinary recurrent network',rule:'Rule-based control',random:'Random-action control'};
const pct=(value?:number)=>value===undefined?'--':`${Math.round(value*100)}%`;
const fitness=(value?:number)=>typeof value==='number'&&Number.isFinite(value)?value.toFixed(1):'--';
export function ResearchDashboard({engine}:{engine:Engine}){
 const overview=engine.research,lineage=engine.lineage,ladder=engine.ladder,cert=overview?.certified_level;
 const champion=overview?.current_champion,best=overview?.best_ever_candidate,latest=overview?.latest_candidate,today=overview?.today,comparison=engine.topologyStatus?.comparisons??[];
 return <section className="research-page"><div className="research-hero"><div><div className="eyebrow">LOCAL RESEARCH STATE</div><h2>Day {today?.day??'--'}</h2><p>Persisted experiment records, candidate lineage, ladder progress and topology-control status.</p></div><button className="subtle refresh-research" onClick={()=>void engine.fetchResearch()}>Refresh status ↻</button></div>
  <div className="research-overview"><section><small>CURRENT CHAMPION</small><strong>{champion?.checkpoint_id??engine.checkpoint}</strong><span>{champion?champion.selection:'seed or existing canonical checkpoint'}</span></section><section><small>CERTIFIED LEVEL</small><strong>{cert?`${cert.level} / 10`:'0 / 10'}</strong><span>{cert?`${cert.level_version} · ${pct(cert.win_rate)} over ${cert.matches} matches`:'No certification recorded yet'}</span></section><section><small>NEXT LEVEL PROGRESS</small><strong>{latest?.validation_metrics?.level_version??'L01-v1'}</strong><span>{latest?.validation_metrics?.win_rate!==undefined?`${pct(latest.validation_metrics.win_rate)} · ${latest.status}`:'Run research:once to record progress'}</span></section><section><small>TRAINING STATUS</small><strong>{overview?.training_status??(engine.training?.status==='training'?'running':'idle')}</strong><span>Live process state, separate from completed results</span></section></div>
  <div className="today-strip"><span>TODAY</span><b>{today?.matches_simulated??0}</b> matches <b>{today?.experiments_completed??0}</b> experiments <b>{today?.candidates_evaluated??overview?.counts?.candidates??0}</b> candidates <b>{today?.promotions??0}</b> promotions</div>
  <div className="research-sections"><section><h3>Champion History</h3><p>{champion?'Latest promoted champion is append-only in the registry.':'No local registry champion has been recorded yet.'}</p><dl><dt>Best-ever candidate</dt><dd>{best?.id??'none recorded'}</dd><dt>Best training fitness</dt><dd>{fitness(best?.training_metrics?.fitness)}</dd><dt>Latest candidate</dt><dd>{latest?.id??'none recorded'}</dd><dt>Latest status</dt><dd>{latest?.status??'--'}</dd></dl></section>
   <section><h3>10-Level Ladder</h3><p>{ladder?`${ladder.version} · strongest legal benchmark is Level 10. No public superhuman claim is implied.`:'Ladder manifest unavailable while brain service is offline.'}</p><div className="ladder-mini">{ladder?.levels?.map(level=><span key={level.version} className={cert&&level.index<=cert.level?'cleared':''} title={`${level.difficulty} · ${level.profile} · ${level.min_matches} matches`}>{String(level.index).padStart(2,'0')}</span>)}</div></section>
   <section><h3>Topology Controls</h3><p>{today?.topology_experiments_status??'Conditions are defined for real, degree-preserving randomized, weight-shuffled, matched recurrent, direct, rule and random baselines. Fair-control conclusions require completed runs.'}</p></section>
   <section><h3>Human Challenge</h3><p>Fight the Fly Brain uses the selected canonical champion. Anonymous leaderboard storage is local and only accepts replay-verified match results.</p><button className="primary" onClick={()=>{engine.setMode('human');}}>Fight the Fly Brain ↗</button></section></div>
  {comparison.length>0&&<section className="topology-comparison"><div className="lab-section-title"><span>Topology Evidence Batch</span><small>Initial bounded data, no superiority claim</small></div><div className="comparison-table">{comparison.slice(0,18).map(row=><div key={row.id}><b>{row.metrics.condition??row.suite.split(':').at(-1)}</b><span>{row.metrics.status??'recorded'}</span><span>{row.metrics.seed??'--'}</span><span>{pct(row.metrics.win_rate)}</span><span>{fitness(row.metrics.mean_reward)}</span><span>{row.metrics.compute?.cpu_seconds?.toFixed(2)??'--'}s</span></div>)}</div></section>}
  <section className="lineage-view"><div className="lab-section-title"><span>Candidate Lineage</span><small>Negative branches stay visible</small></div>{lineage?.nodes?.length?<div className="lineage-list">{lineage.nodes.slice(-24).map(node=><div key={node.id} className={`lineage-node ${node.status}`}><b>{node.champion?'Champion':'Candidate'}</b><strong>{node.id}</strong><span>parent {node.parent_id??node.parent_champion_id??'seed'} · {node.trainer} · generation {node.generation}</span><small>{node.status}{node.reason&&Object.keys(node.reason).length?` · ${Object.values(node.reason).join(', ')}`:''}</small></div>)}</div>:<p className="empty-lineage">No registry lineage yet. Run <code>npm run research:once -- --tiny --ladder-matches 4</code> for a bounded local dry run.</p>}</section>
 </section>;
}
export function Research({engine}:{engine:Engine}){
 const g=engine.graph,s=engine.state;
 return <details className="research-details"><summary>Research details <span>Data, wiring, seeds and comparison controls</span></summary><div className="research-body"><div className="research-grid"><section><h3>Biological data</h3><p>{g?.synthetic?'Synthetic fixture; no biological graph is active.':g?'FlyWire v783 connectivity and synapse counts. This controller uses a selected subgraph, not the entire brain.':'Fly Brain engine offline; no biological controller is active.'}</p><dl><dt>Active neurons</dt><dd>{g?.neurons.toLocaleString()??0}</dd><dt>Connections (directed edges)</dt><dd>{g?.edge_count.toLocaleString()??0}</dd><dt>Neurons drawn</dt><dd>{g?.ids.length??0}</dd><dt>Stimulated / read out</dt><dd>{g?.input_count??0} / {g?.output_count??0}</dd></dl></section><section><h3>Fixed and trainable</h3><p>Fly wiring and biological connection strengths stay fixed. The game uses normalized recurrent weights and approximate dynamics. Only the artificial sensory adapter and motor readout can train in Train mode.</p><p>Nothing learns during a match. Candidate snapshots never overwrite the canonical model from the browser.</p><dl><dt>Brain update time</dt><dd>{engine.brainMs.toFixed(2)} ms</dd><dt>Game update time</dt><dd>{engine.gameMs.toFixed(2)} ms</dd><dt>Average |activity|</dt><dd>{engine.aggregate.toFixed(5)}</dd><dt>Snapshot</dt><dd>{engine.checkpoint}</dd></dl></section><section><h3>Reproduce or compare</h3><label>Match seed<input aria-label="Match seed" type="number" min="0" max="4294967295" defaultValue={s.seed} key={s.seed} onBlur={e=>{const seed=Number(e.target.value);if(Number.isInteger(seed)&&seed>=0&&seed<=4294967295&&seed!==s.seed)engine.reset(seed);}}/></label><label>Research controller<select aria-label="Research controller" value={engine.topology} onChange={e=>{engine.topology=e.target.value as Topology;engine.requestedCheckpoint='';engine.reset();}}>{Object.entries(TOPOLOGY_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><p>Randomized controls are derived comparisons, not the original biological topology. Rule and random baselines activate zero neurons.</p></section></div><details className="input-details"><summary>All 20 inputs and the sensory-to-motor interface</summary><p>Artificial game inputs stimulate sensory candidate neurons. Eight recurrent updates carry activity through the frozen graph. Only descending candidate activity reaches the trainable 14-action readout. There is no direct observation bypass.</p><div className="channels">{CHANNELS.map((name,i)=><div key={name}><span>{String(i+1).padStart(2,'0')} {name}</span><b>{observation(s,1)[i].toFixed(3)}</b></div>)}</div></details><p className="technical-note">Data hash: {g?.dataset_hash??'Unavailable'}. Colors distinguish input, internal and output roles. Positive/negative links show the effective model sign; they do not establish receptor-level biology. Display coordinates are schematic.</p></div></details>;
}

