import {CHANNELS,type Topology} from '../../../packages/protocol';
import {observation} from '../../../packages/sim/core';
import type {Engine} from './engine';
export const TOPOLOGY_LABELS:Record<Topology,string>={real:'Fly Brain wiring',degree_randomized:'Randomized wiring · same degrees',weight_shuffled:'Shuffled connection weights',ordinary:'Ordinary recurrent network',rule:'Rule-based control',random:'Random-action control'};
export function Research({engine}:{engine:Engine}){
 const g=engine.graph,s=engine.state;
 return <details className="research-details"><summary>Research details <span>Data, wiring, seeds and comparison controls</span></summary><div className="research-body"><div className="research-grid"><section><h3>Biological data</h3><p>{g?.synthetic?'Synthetic fixture; no biological graph is active.':g?'FlyWire v783 connectivity and synapse counts. This controller uses a selected subgraph, not the entire brain.':'Fly Brain engine offline; no biological controller is active.'}</p><dl><dt>Active neurons</dt><dd>{g?.neurons.toLocaleString()??0}</dd><dt>Connections (directed edges)</dt><dd>{g?.edge_count.toLocaleString()??0}</dd><dt>Neurons drawn</dt><dd>{g?.ids.length??0}</dd><dt>Stimulated / read out</dt><dd>{g?.input_count??0} / {g?.output_count??0}</dd></dl></section><section><h3>Fixed and trainable</h3><p>Fly wiring and biological connection strengths stay fixed. The game uses normalized recurrent weights and approximate dynamics. Only the artificial sensory adapter and motor readout can train in Train mode.</p><p>Nothing learns during a match. Candidate snapshots never overwrite the canonical model from the browser.</p><dl><dt>Brain update time</dt><dd>{engine.brainMs.toFixed(2)} ms</dd><dt>Game update time</dt><dd>{engine.gameMs.toFixed(2)} ms</dd><dt>Average |activity|</dt><dd>{engine.aggregate.toFixed(5)}</dd><dt>Snapshot</dt><dd>{engine.checkpoint}</dd></dl></section><section><h3>Reproduce or compare</h3><label>Match seed<input aria-label="Match seed" type="number" min="0" max="4294967295" defaultValue={s.seed} key={s.seed} onBlur={e=>{const seed=Number(e.target.value);if(Number.isInteger(seed)&&seed>=0&&seed<=4294967295&&seed!==s.seed)engine.reset(seed);}}/></label><label>Research controller<select aria-label="Research controller" value={engine.topology} onChange={e=>{engine.topology=e.target.value as Topology;engine.requestedCheckpoint='';engine.reset();}}>{Object.entries(TOPOLOGY_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><p>Randomized controls are derived comparisons, not the original biological topology. Rule and random baselines activate zero neurons.</p></section></div><details className="input-details"><summary>All 20 inputs and the sensory-to-motor interface</summary><p>Artificial game inputs stimulate sensory candidate neurons. Eight recurrent updates carry activity through the frozen graph. Only descending candidate activity reaches the trainable 14-action readout. There is no direct observation bypass.</p><div className="channels">{CHANNELS.map((name,i)=><div key={name}><span>{String(i+1).padStart(2,'0')} {name}</span><b>{observation(s,1)[i].toFixed(3)}</b></div>)}</div></details><p className="technical-note">Data hash: {g?.dataset_hash??'Unavailable'}. Colors distinguish input, internal and output roles. Positive/negative links show the effective model sign; they do not establish receptor-level biology. Display coordinates are schematic.</p></div></details>;
}

